### ISSUE TITLE
CirrusCI is failing and blocking PRs

### ISSUE THREAD

**Issue by sudden6** [TokTok/c-toxcore#1313]
For e.g. https://github.com/TokTok/c-toxcore/pull/1311 CirrusCI is failing with the following output:
```
bazel test -c opt -k //c-toxcore/...
Starting local Bazel server and connecting to it...
�[32mINFO: �[0mInvocation ID: b472ed64-93f6-4154-b722-fbb5eec43848
�[32mLoading:�[0m 
�[32mLoading:�[0m 0 packages loaded
�[32mLoading:�[0m 0 packages loaded
�[31m�[1mERROR: �[0m/tmp/cirrus-ci-build/WORKSPACE:45:1: Traceback (most recent call last):
	File "/tmp/cirrus-ci-build/WORKSPACE", line 45
		skydoc_repositories()
	File "/home/cirrus/.cache/bazel/_bazel_cirrus/b3ae12dd079012e10ed112b1996c540f/external/io_bazel_skydoc/skylark/skylark.bzl", line 307, in skydoc_repositories
		native.http_archive(name = "protobuf", url = "https://...", <2 more arguments>)
type 'struct' has no method http_archive()
�[31m�[1mERROR: �[0mError evaluating WORKSPACE file
�[31m�[1mERROR: �[0merror loading package '': Encountered error while reading extension file 'haskell/ghc_bindist.bzl': no such package '@io_tweag_rules_haskell//haskell': error loading package 'external': Could not load //external package
�[31m�[1mERROR: �[0merror loading package '': Encountered error while reading extension file 'haskell/ghc_bindist.bzl': no such package '@io_tweag_rules_haskell//haskell': error loading package 'external': Could not load //external package
�[31m�[1mERROR: �[0mSkipping '//c-toxcore/...': no targets found beneath 'c-toxcore'
�[35mWARNING: �[0mTarget pattern parsing failed.
�[31m�[1mERROR: �[0merror loading package '': Encountered error while reading extension file 'haskell/ghc_bindist.bzl': no such package '@io_tweag_rules_haskell//haskell': error loading package 'external': Could not load //external package
�[32mINFO: �[0mElapsed time: 3.337s
�[32mINFO: �[0m0 processes.
�[31m�[1mFAILED:�[0m Build did NOT complete successfully (0 packages loaded)
�[31m�[1mERROR: �[0mCouldn't start the build. Unable to run tests
�[31m�[1mFAILED:�[0m Build did NOT complete successfully (0 packages loaded)
�[0m
Exit status: 2
```

What is this supposed to test? Is it still needed?

ping: @iphydf @robinlinden

**Comment by nurupo** [comment]
Did #1314 fix it?

**Comment by sudden6** [comment]
yeah
