### ISSUE TITLE
Crash with persistent grups

### ISSUE THREAD

**Issue by tox-user** [TokTok/c-toxcore#970]
I thought this crash was fixed in newest commits to pgc branch, but apparently not. I'm getting the same crash in toxcore 0.2.3 with pgc.

Commit hash: 5b6d1129ca9b4eff4781315d622382d471b1745e

Backtrace is the same as last time:
```
#0  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2805
#1  0x00007ffff416582b in group_peername () from /usr/local/lib/libtoxcore.so.2
#2  0x00007ffff416dfec in tox_conference_peer_get_name () from /usr/local/lib/libtoxcore.so.2
#3  0x0000555555808688 in Core::getGroupPeerNames(int) const ()
#4  0x000055555581f129 in Group::regeneratePeerList() ()
#5  0x000055555578e9f5 in Widget::onGroupPeerlistChanged(int) ()
#6  0x000055555572f853 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<int>, void, void (Widget::*)(int)>::call(void (Widget::*)(int), Widget*, void**) ()
#7  0x000055555572e9bc in void QtPrivate::FunctionPointer<void (Widget::*)(int)>::call<QtPrivate::List<int>, void>(void (Widget::*)(int), Widget*, void**) ()
#8  0x000055555572da01 in QtPrivate::QSlotObject<void (Widget::*)(int), QtPrivate::List<int>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#9  0x00007ffff0196499 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff76ac46b in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff77ab92b in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x000055555578fbe8 in Widget::event(QEvent*) ()
#13 0x00007ffff7664b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff766c341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff01699e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff016c16d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff01bdc43 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff28997f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff2899a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff2899b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff01be04f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff01679ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff017013c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x000055555571b02f in main ()
```

**Comment by tox-user** [comment]
The commit that fixes it wasn't merged when I compiled. Now it is, so it shouldn't happen anymore.
